apiVersion: apps/v1
kind: Deployment
metadata:
    name: mecanica-xpto-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mecanica-xpto-api
    template:
        metadata:
            labels:
                app: mecanica-xpto-api
        spec:
            containers:
              - name: mecanica-xpto-api
                image: mandaapagdocker/mecanica-xpto-api:1.0.0
                ports:
                  - containerPort: 8080
                env:
                  - name: POSTGRES_USER
                    value: admin_user
                  - name: POSTGRES_PASSWORD
                    value: Senha123
                  - name: POSTGRES_DB
                    value: db_mecanica_xpto
                  - name: POSTGRES_HOST
                    value: db
                  - name: POSTGRES_PORT
                    value: "5432"
                volumeMounts:
                  - mountPath: /app/data
                    name: app_data
            hostNetwork: true