apiVersion: apps/v1
kind: Deployment
metadata:
    name: mecanica-xpto-deployment
spec:
    replicas: 3
    selector:
        matchLabels:
            app: dev
    template:
        metadata:
            labels:
                app: dev
        spec:
            containers:
              - name: dev
                image: golang:1.24
                volumeMounts:
                  - mountPath: .:/app
                    name: dev_data
                command: ["tail", "-f", "/dev/null"]
                tty: true
                workingDir: /app
            hostNetwork: true
