name: Docker Image CI

on:
  push:
    branches: [ "feature/*", "enhancement/*", "bugfix/*", "hotfix/*", "release/*" ]
  pull_request:
    branches: [ "release/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and tag Docker image
        run: |
          docker build . --file Dockerfile